### ISSUE TITLE
Issue with resolving relations.

### ISSUE THREAD

**Issue by deep-c** [fenos/graphql-thinky#9]
Hi,

I am attempting to define a relation on createModelType however I am getting:
```
C:\Users\Deep\Projects\chat\node_modules\graphql-thinky\lib\index.js:184            
        relation.relationName = related;
TypeError: Cannot set property 'relationName' of undefined
```

Stacktrace as follows:
```
TypeError: Cannot set property 'relationName' of undefined                          
    at GraphqlThinky.node (C:\Users\Deep\Projects\chat\node_modules\graphql-thinky\l
ib\index.js:184:31)                                                                 
    at GraphqlThinky.resolve (C:\Users\Deep\Projects\chat\node_modules\graphql-think
y\lib\index.js:81:24)                                                               
    at Object.fields (C:/Users/Deep/Projects/chat/server/graphql/channelType.js:12:2
2)                                                                                  
    at fields (C:\Users\Deep\Projects\chat\node_modules\graphql-thinky\lib\modelToGq
lObjectType.js:38:41)                                                               
    at resolveThunk (C:\Users\Deep\Projects\chat\node_modules\graphql\type\definitio
n.js:115:40)                                                                        
    at defineFieldMap (C:\Users\Deep\Projects\chat\node_modules\graphql\type\definit
ion.js:265:18)                                                                      
    at GraphQLObjectType.getFields (C:\Users\Deep\Projects\chat\node_modules\graphql
\type\definition.js:235:44)                                                         
    at C:\Users\Deep\Projects\chat\node_modules\graphql\type\schema.js:207:27       
    at typeMapReducer (C:\Users\Deep\Projects\chat\node_modules\graphql\type\schema.
js:219:7)                                                                           
    at typeMapReducer (C:\Users\Deep\Projects\chat\node_modules\graphql\type\schema.
js:187:12)                                                                          
    at C:\Users\Deep\Projects\chat\node_modules\graphql\type\schema.js:217:22       
    at Array.forEach (native)                                                       
    at C:\Users\Deep\Projects\chat\node_modules\graphql\type\schema.js:208:29       
    at typeMapReducer (C:\Users\Deep\Projects\chat\node_modules\graphql\type\schema.
js:219:7)                                                                           
    at Array.reduce (native)                                                        
    at new GraphQLSchema (C:\Users\Deep\Projects\chat\node_modules\graphql\type\sche
ma.js:95:34)                                                                        
    at Object.<anonymous> (C:/Users/Deep/Projects/chat/server/graphql/schema.js:4:16
)                                                                                   
    at Module._compile (module.js:556:32)                                           
    at loader (C:\Users\Deep\Projects\chat\node_modules\babel-register\lib\node.js:1
44:5)                                                                               
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Deep\Projec
ts\chat\node_modules\babel-register\lib\node.js:154:7)                              
    at Module.load (module.js:473:32)                                               
    at tryModuleLoad (module.js:432:12)
```

My models are as follows:

Channels Model
```
import thinky from '../../utils/thinky'

const type = thinky.type
const Channels = thinky.createModel("Channels", {
    id: type.string().uuid(4).required(),
    name: type.string().required(),
    description: type.string(),
    isPrivate: type.boolean().default(false),
    createdOn: type.date().default(new Date()),
    isClosed: type.boolean().default(false),
    teamName: type.string().allowNull(false)
}, {
    pk: 'id'
})

Channels.relations = () => {
    Channels.belongsTo(thinky.models.Teams, 'team', 'teamName', 'name')
    // Channels.belongsTo(Users, 'members', 'id', 'id')
}

export default Channels
```

Teams Model
```
import thinky from '../../utils/thinky'


const type = thinky.type
const Teams = thinky.createModel("Teams", {
    name: type.string().required(),
    description: type.string(),    
    createdOn: type.date().default(new Date()),
    isClosed: type.boolean().default(false),
}, {
    pk: 'name'
});

Teams.relations = () => {
    Teams.hasMany(thinky.models.Channels, 'channels', 'name', 'teamName')
    // Teams.belongsTo(Users, 'members', 'name', 'id')    
}

export default Teams
```

channelType - file where stacktrace includes
```
import teamType from './teamType'
import GT from '../../utils/graphql-thinky'


const { resolve } = GT;

// export default GT.createModelType('Channels')
export default GT.createModelType('Channels', {
    fields: () => ({
        team: {
            type: teamType,
            resolve: resolve('Channels', 'team')
        }
    })
})
```

teamType
```
import channelType from './channelType'
import GT from '../../utils/graphql-thinky'


const { resolve } = GT;

export default GT.createModelType('Teams', {
    fields: () => ({
        channels: {
            type: channelType,
            resolve: resolve('Teams', 'channels')
        }
    })
})
```
Any help would be appreciated. Thanks

**Comment by fenos** [comment]
Hi @deep-c which version are you using 0.3.0 or 0.4-beta? I will glad to help you

**Comment by deep-c** [comment]
Hey fenos, i am using 0.4.0-beta-3. Thanks

**Comment by fenos** [comment]
Hi, @deep-c I found out the issue. The problem is that the relation **channels** hasn't been registered.
Are you sure you are calling `Model.relations()` before passing `thinky` instance into **GraphQL-thinky**?

Look this line of the example: [run relations](https://github.com/fenos/graphql-thinky/blob/dataloader/example/app/models/index.js#L15)

The line that causes that bad stack trace is this: [Bug-line](https://github.com/fenos/graphql-thinky/blob/dataloader/src/index.js#L204)

It should be moved after the relation check so a more helpful message will be thrown.
I'll prepare a fix for that

**Comment by deep-c** [comment]
Awesome, thanks for that. Relations working however im having another issue `GraphQL-thinky couldn't find any loaders set on the GraphQL context\n          with the key \"loaders\"\n` when attempting to pass a graphql query with a `joined` field. I think its the same issue from #7 

```
{
  teams {
    name
    createdOn
    channels {
      id
    }
  }
}
```

With the following response from the graph endpoint.

```
{
  "data": {
    "teams": [
      {
        "name": "kkona",
        "createdOn": "Fri Nov 04 2016 20:38:44 GMT+1100 (AUS Eastern Daylight Time)",
        "channels": null
      }
    ]
  },
  "errors": [
    {
      "message": "\n          GraphQL-thinky couldn't find any loaders set on the GraphQL context\n          with the key \"loaders\"\n        ",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ]
    }
  ]
}
```

**Comment by fenos** [comment]
@deep-c Great to hear that, I missed the last comment on that Issue. I answered there #7 , Let me know if that helps 👍 After that you should be able to resolve any relation
